 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
 * Debugger is active!
 * Debugger PIN: 140-457-053
Traceback (most recent call last):
  File "/Users/lijunliang/PycharmProjects/PythonProject3/app.py", line 62, in <module>
    app.run(debug=True)
  File "/opt/anaconda3/lib/python3.12/site-packages/flask/app.py", line 625, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/opt/anaconda3/lib/python3.12/site-packages/werkzeug/serving.py", line 1106, in run_simple
    run_with_reloader(
  File "/opt/anaconda3/lib/python3.12/site-packages/werkzeug/_reloader.py", line 448, in run_with_reloader
    ensure_echo_on()
  File "/opt/anaconda3/lib/python3.12/site-packages/werkzeug/_reloader.py", line 428, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
